[package]
name = "genetic_algorithm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
getopts = "0.2.21"
rand = "0.8.5"
rand_distr = "0.4.3"
random = "0.14.0"
